#!/usr/bin/env bash

set -e  # stop script on any error
set -o pipefail

# Colors for nicer output
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
NC="\033[0m" # no color

echo -e "${YELLOW}
====================================
|  Formatting code with ktlintFormat...
====================================
${NC}"

./gradlew ktlintFormat


echo -e "${YELLOW}
====================================
|  Running ktlintCheck...
====================================
${NC}"

if ! ./gradlew --no-daemon --stacktrace -PdisablePreDex ktlintCheck; then
  echo -e "${RED}❌ Ktlint check failed.${NC}"
  exit 1
fi

echo -e "${GREEN}✔ All Ktlint checks passed successfully!${NC}"
exit 0
